from model.mysql.connection import create_connection


QUERY_INIT = """
-- MySQL Script generated by MySQL Workbench
-- Sun Jan 15 14:22:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FarmMarkets
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FarmMarkets` ;

-- -----------------------------------------------------
-- Schema FarmMarkets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FarmMarkets` DEFAULT CHARACTER SET utf8 ;
USE `FarmMarkets` ;

-- -----------------------------------------------------
-- Table `FarmMarkets`.`Markets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FarmMarkets`.`Markets` ;

CREATE TABLE IF NOT EXISTS `FarmMarkets`.`Markets` (
  `idMarkets` INT NOT NULL AUTO_INCREMENT,
  `marketname` VARCHAR(100) NOT NULL,
  `updatetime` DATETIME NULL,
  `fmid` INT NOT NULL,
  PRIMARY KEY (`idMarkets`),
  UNIQUE INDEX `fmid_UNIQUE` (`fmid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmMarkets`.`Counties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FarmMarkets`.`Counties` ;

CREATE TABLE IF NOT EXISTS `FarmMarkets`.`Counties` (
  `idCounties` INT NOT NULL AUTO_INCREMENT,
  `county` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCounties`),
  UNIQUE INDEX `County_UNIQUE` (`county` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmMarkets`.`Zips`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FarmMarkets`.`Zips` ;

CREATE TABLE IF NOT EXISTS `FarmMarkets`.`Zips` (
  `idZips` INT NOT NULL AUTO_INCREMENT,
  `zip` VARCHAR(100) NULL,
  PRIMARY KEY (`idZips`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmMarkets`.`States`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FarmMarkets`.`States` ;

CREATE TABLE IF NOT EXISTS `FarmMarkets`.`States` (
  `idStates` INT NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idStates`),
  UNIQUE INDEX `state_UNIQUE` (`state` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmMarkets`.`Cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FarmMarkets`.`Cities` ;

CREATE TABLE IF NOT EXISTS `FarmMarkets`.`Cities` (
  `idCities` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(100) NULL,
  PRIMARY KEY (`idCities`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmMarkets`.`Locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FarmMarkets`.`Locations` ;

CREATE TABLE IF NOT EXISTS `FarmMarkets`.`Locations` (
  `idLocations` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(200) NULL,
  `x` VARCHAR(45) NULL,
  `y` VARCHAR(45) NULL,
  `location` VARCHAR(100) NULL,
  `Markets_idMarkets` INT NOT NULL,
  `Counties_idCounties` INT NULL,
  `Zips_idZips` INT NULL,
  `States_idStates` INT NULL,
  `Cities_idCities` INT NULL,
  PRIMARY KEY (`idLocations`),
  INDEX `fk_Location_Markets1_idx` (`Markets_idMarkets` ASC) VISIBLE,
  INDEX `fk_Locations_Counties1_idx` (`Counties_idCounties` ASC) VISIBLE,
  INDEX `fk_Locations_Zips1_idx` (`Zips_idZips` ASC) VISIBLE,
  INDEX `fk_Locations_States1_idx` (`States_idStates` ASC) VISIBLE,
  INDEX `fk_Locations_Cities1_idx` (`Cities_idCities` ASC) VISIBLE,
  CONSTRAINT `fk_Location_Markets1`
    FOREIGN KEY (`Markets_idMarkets`)
    REFERENCES `FarmMarkets`.`Markets` (`idMarkets`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locations_Counties1`
    FOREIGN KEY (`Counties_idCounties`)
    REFERENCES `FarmMarkets`.`Counties` (`idCounties`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locations_Zips1`
    FOREIGN KEY (`Zips_idZips`)
    REFERENCES `FarmMarkets`.`Zips` (`idZips`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locations_States1`
    FOREIGN KEY (`States_idStates`)
    REFERENCES `FarmMarkets`.`States` (`idStates`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locations_Cities1`
    FOREIGN KEY (`Cities_idCities`)
    REFERENCES `FarmMarkets`.`Cities` (`idCities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmMarkets`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FarmMarkets`.`Categories` ;

CREATE TABLE IF NOT EXISTS `FarmMarkets`.`Categories` (
  `idCategories` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategories`),
  UNIQUE INDEX `Category_UNIQUE` (`category` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmMarkets`.`Markets_has_Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FarmMarkets`.`Markets_has_Categories` ;

CREATE TABLE IF NOT EXISTS `FarmMarkets`.`Markets_has_Categories` (
  `Markets_idMarkets` INT NOT NULL,
  `Categories_idCategories` INT NOT NULL,
  PRIMARY KEY (`Markets_idMarkets`, `Categories_idCategories`),
  INDEX `fk_Markets_has_Categories_Categories1_idx` (`Categories_idCategories` ASC) VISIBLE,
  INDEX `fk_Markets_has_Categories_Markets1_idx` (`Markets_idMarkets` ASC) VISIBLE,
  CONSTRAINT `fk_Markets_has_Categories_Markets1`
    FOREIGN KEY (`Markets_idMarkets`)
    REFERENCES `FarmMarkets`.`Markets` (`idMarkets`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Markets_has_Categories_Categories1`
    FOREIGN KEY (`Categories_idCategories`)
    REFERENCES `FarmMarkets`.`Categories` (`idCategories`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmMarkets`.`Payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FarmMarkets`.`Payments` ;

CREATE TABLE IF NOT EXISTS `FarmMarkets`.`Payments` (
  `idPayments` INT NOT NULL AUTO_INCREMENT,
  `payment` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPayments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmMarkets`.`Markets_has_Payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FarmMarkets`.`Markets_has_Payments` ;

CREATE TABLE IF NOT EXISTS `FarmMarkets`.`Markets_has_Payments` (
  `Markets_idMarkets` INT NOT NULL,
  `Payments_idPayments` INT NOT NULL,
  PRIMARY KEY (`Markets_idMarkets`, `Payments_idPayments`),
  INDEX `fk_Markets_has_Payments_Payments1_idx` (`Payments_idPayments` ASC) VISIBLE,
  INDEX `fk_Markets_has_Payments_Markets1_idx` (`Markets_idMarkets` ASC) VISIBLE,
  CONSTRAINT `fk_Markets_has_Payments_Markets1`
    FOREIGN KEY (`Markets_idMarkets`)
    REFERENCES `FarmMarkets`.`Markets` (`idMarkets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Markets_has_Payments_Payments1`
    FOREIGN KEY (`Payments_idPayments`)
    REFERENCES `FarmMarkets`.`Payments` (`idPayments`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmMarkets`.`Media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FarmMarkets`.`Media` ;

CREATE TABLE IF NOT EXISTS `FarmMarkets`.`Media` (
  `Markets_idMarkets` INT NOT NULL,
  `youtube` VARCHAR(200) NULL,
  `facebook` VARCHAR(200) NULL,
  `website` VARCHAR(200) NULL,
  `othermedia` VARCHAR(200) NULL,
  INDEX `fk_Seasons_Markets1_idx` (`Markets_idMarkets` ASC) VISIBLE,
  CONSTRAINT `fk_Media_Markets1`
    FOREIGN KEY (`Markets_idMarkets`)
    REFERENCES `FarmMarkets`.`Markets` (`idMarkets`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmMarkets`.`Seasons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FarmMarkets`.`Seasons` ;

CREATE TABLE IF NOT EXISTS `FarmMarkets`.`Seasons` (
  `Markets_idMarkets` INT NOT NULL,
  `season1` VARCHAR(100) NULL,
  `season1_time` VARCHAR(200) NULL,
  `season2` VARCHAR(100) NULL,
  `season2_time` VARCHAR(200) NULL,
  `season3` VARCHAR(100) NULL,
  `season3_time` VARCHAR(200) NULL,
  `season4` VARCHAR(100) NULL,
  `season4_time` VARCHAR(200) NULL,
  INDEX `fk_Media_Markets1_idx` (`Markets_idMarkets` ASC) VISIBLE,
  CONSTRAINT `fk_Seasons_Markets1`
    FOREIGN KEY (`Markets_idMarkets`)
    REFERENCES `FarmMarkets`.`Markets` (`idMarkets`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmMarkets`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FarmMarkets`.`Users` ;

CREATE TABLE IF NOT EXISTS `FarmMarkets`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(155) NOT NULL,
  `secondname` VARCHAR(155) NOT NULL,
  `email` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmMarkets`.`Reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FarmMarkets`.`Reviews` ;

CREATE TABLE IF NOT EXISTS `FarmMarkets`.`Reviews` (
  `idReviews` INT NOT NULL AUTO_INCREMENT,
  `Markets_idMarkets` INT NOT NULL,
  `Users_idUsers` INT NOT NULL,
  `rate` INT NOT NULL,
  `review` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idReviews`),
  INDEX `fk_Reviews_Markets1_idx` (`Markets_idMarkets` ASC) VISIBLE,
  INDEX `fk_Reviews_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_Reviews_Markets1`
    FOREIGN KEY (`Markets_idMarkets`)
    REFERENCES `FarmMarkets`.`Markets` (`idMarkets`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reviews_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `FarmMarkets`.`Users` (`idUsers`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
"""


def db_init():
    status, answer = create_connection()
    if status is True:
        db = answer
        cursor = db.cursor()
        cursor.execute(QUERY_INIT)
        db.close()
        print("Database was created successfully")
    else:
        print(answer)


def main():
    db_init()


if __name__ == "__main__":
    main()
